version: "3.9"

services:
  web:
    build: .
    container_name: fastapi_app
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    environment:
      DATABASE_URL: mysql+pymysql://root:luna123456@localhost:3306/fastapi
    volumes:
      # 开发环境下可使用挂载，实时更新代码（生产环境可以去掉）
      - ./:/app
